module.exports = {
  1: {
    phrase: 'І аб чом же у нас будєт разгавор?',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '101',
    telegramStickerId: 'CAADAgADBAAD09KeCnfMl_xO0kSQAg',
  },
  2: {
    phrase: 'Я етого нє люблю',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '23',
    telegramStickerId: 'CAADAgADCAAD09KeCtGzuj4pydzrAg',
  },
  3: {
    phrase: 'Ну нє абіжайся',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '53',
    telegramStickerId: 'CAADAgADCQAD09KeCsntGtCPqKDIAg',
  },
  4: {
    phrase: 'Єсть',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '85',
    telegramStickerId: 'CAADAgADCgAD09KeClr9ZjkHoEBbAg',
  },
  5: {
    phrase: 'Ну как ето об чьом, Васіліса Єгоровна? Разниє єсть інтєрєсниє для нас обоїх вєщі',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '103',
    telegramStickerId: '',
  },
  6: {
    phrase: 'Мінє оні уже давно нє інтєрєсниє еті вєщі',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '106',
    telegramStickerId: 'CAADAgADCwAD09KeCrwL3nrMBuz',
  },
  7: {
    phrase: 'Ето, Вася, шо, нада понімать как визов?',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '109',
    telegramStickerId: 'CAADAgADDAAD09KeCiuvBB5ohNT8Ag',
  },
  8: {
    phrase: 'Ні, то нє, то я так',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '124',
    telegramStickerId: 'CAADAgADDQAD09KeCp__ooxRu1DmAg',
  },
  9: {
    phrase: 'А ти хуй в бєлки видів?',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '139',
    telegramStickerId: 'CAADAgADDgAD09KeCrj7rRDLaF8nAg',
  },
  10: {
    phrase: 'Ну шо як відімость?',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '162',
    telegramStickerId: '',
  },
  11: {
    phrase: 'Та, то найобки єщо хуйня',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '168',
    telegramStickerId: 'CAADAgADDwAD09KeCntwXnKhIseBAg',
  },
  12: {
    phrase: 'А мої прєдки були дворянє',
    play: 'Васiлiса Егоровна i мужичкi',
    phraseN: '222',
    telegramStickerId: 'CAADAgADEAAD09KeCooWmyZ53gniAg',
  },
  13: {
    phrase: 'Блядські ці питання зайобують',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '27',
    telegramStickerId: 'CAADAgADEQAD09KeCszSKZNdwvvVAg',
  },
  14: {
    phrase:
      'Про наслідки можливі не подумать? Один лиш тільки раз і вже крадеться піздець з своєю усмішкою хижой',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '28',
    telegramStickerId: '',
  },
  15: {
    phrase: 'Такіє варіанти єбав я в рот і в носа',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '30',
    telegramStickerId: 'CAADAgADEgAD09KeCtTX4Noq63rbAg',
  },
  16: {
    phrase: 'Не можна мстить. Повинні ми любити всіх підорасів, злодіїв, убивць',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '59',
    telegramStickerId: '',
  },
  17: {
    phrase: 'Хуйова мода',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '70',
    telegramStickerId: '',
  },
  18: {
    phrase: 'Но це, конєшно, в смислє пєрєносном',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '72',
    telegramStickerId: 'CAADAgADEwAD09KeClXixfOQETv5Ag',
  },
  19: {
    phrase: 'О часи, о Данія нещасна!',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '74',
    telegramStickerId: 'CAADAgADFAAD09KeCtBLuwZWc_KDAg',
  },
  20: {
    phrase: 'Шось пиздите таке, що не просцяти і за цілий тиждень',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '77',
    telegramStickerId: 'CAADAgADFQAD09KeCjmNApx8r9FDAg',
  },
  21: {
    phrase: 'Сучій сину, хуйовий нєдоносок! Так на батька! Таку хуйню казать!',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '89',
    telegramStickerId: 'CAADAgADFgAD09KeCn0hMHVM_oYcAg',
  },
  22: {
    phrase: 'Бешкетнику…',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '122',
    telegramStickerId: 'CAADAgADFwAD09KeCmA2QGVt2B31Ag',
  },
  23: {
    phrase: 'Щас піздець вам буде, слівайте воду, йобані масони, чи як вас там',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '131',
    telegramStickerId: '',
  },
  24: {
    phrase: 'Шо не ясно?',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '152',
    telegramStickerId: 'CAADAgADGAAD09KeCjdOv1Ub5sSeAg',
  },
  25: {
    phrase: 'Папаша, всьо буде в лучшем відє, не хвилюйтесь',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '154',
    telegramStickerId: 'CAADAgADGQAD09KeCva19FvsZ2JxAg',
  },
  26: {
    phrase: 'Ітоги подвєдьом',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '177',
    telegramStickerId: '',
  },
  27: {
    phrase: 'Ех, блядська Данія! Піздєц всім сподіванням…',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '182',
    telegramStickerId: '',
  },
  28: {
    phrase: 'Завіса',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '192',
    telegramStickerId: 'CAADAgADGgAD09KeCpi-A0DjV6TUAg',
  },
  29: {
    phrase: 'Нє дєлай волни, Хваня',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '52',
    telegramStickerId: 'CAADAgADGwAD09KeCqTBrOnHPzw4Ag',
  },
  30: {
    phrase: 'Блядь, ніхуя не просцу',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '58',
    telegramStickerId: 'CAADAgADHAAD09KeCgoszTR8ZRTGAg',
  },
  31: {
    phrase: 'Ну от, скажіте',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '96',
    telegramStickerId: '',
  },
  32: {
    phrase: 'Об чом ви щас думаєте, Єгорка?',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '141',
    telegramStickerId: 'CAADAgADHQAD09KeCo9-hWO-37nqAg',
  },
  33: {
    phrase: 'А вот етого как раз і ніззя',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '156',
    telegramStickerId: 'CAADAgADHgAD09KeChfW5Ln1EIDIAg',
  },
  34: {
    phrase: 'Как же так, почєму ніззя?',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '159',
    telegramStickerId: '',
  },
  35: {
    phrase: 'А так, ніззя і всьо',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '161',
    telegramStickerId: '',
  },
  36: {
    phrase: 'Ця хуйня тобі не допоможе',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '216',
    telegramStickerId: 'CAADAgADHwAD09KeCldvt3FMEhtoAg',
  },
  37: {
    phrase: 'Пойняв?',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '11',
    telegramStickerId: '',
  },
  38: {
    phrase: 'Пойняв',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '13',
    telegramStickerId: '',
  },
  39: {
    phrase: 'Кому спасібо надо сказать?',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '30',
    telegramStickerId: 'CAADAgADIAAD09KeCjevOvpSDLj8Ag',
  },
  40: {
    phrase: 'Вчити вас, синків, треба, іщо ніхуя служби не пойняли',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '35',
    telegramStickerId: 'CAADAgADIQAD09KeCiA-z24XrfCCAg',
  },
  41: {
    phrase: 'Шо не ясно, йоб твою в дарданели мать',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '41',
    telegramStickerId: 'CAADAgADIgAD09KeCuikdW2PzhYyAg',
  },
  42: {
    phrase: 'Нічого, культурно побазарілі',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '81',
    telegramStickerId: '',
  },
  43: {
    phrase: 'Я так думаю, шо щастя кожний по-своєму понімає',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '85',
    telegramStickerId: 'CAADAgADIwAD09KeCsPFotAHVLsZAg',
  },
  44: {
    phrase: 'Ти посмотрі, какой он бистрий',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '102',
    telegramStickerId: 'CAADAgADawAD09KeCkkf2mSyh71nAg',
  },
  45: {
    phrase: 'Хорош пиздєть',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '105',
    telegramStickerId: 'CAADAgADJAAD09KeChpSFZY9neizAg',
  },
  46: {
    phrase: 'А хто ви такой, пришлі, матюкаєтесь тут, шо такоє?',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '108',
    telegramStickerId: 'CAADAgADbAAD09KeCvuPXCPSL-0-Ag',
  },
  47: {
    phrase: 'Шо, нравіца? На!',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '122',
    telegramStickerId: 'CAADAgADJQAD09KeCnH8e4OzeTQVAg',
  },
  48: {
    phrase: 'А тепер шо робить будем?',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '153',
    telegramStickerId: 'CAADAgADJgAD09KeCo98sVam7wE0Ag',
  },
  49: {
    phrase: 'В етой жизні так, Ваня: хто умнєє, тот і прав',
    play: 'Герой нашого часу. Повість перша',
    phraseN: '161',
    telegramStickerId: 'CAADAgADJwAD09KeCk7SSrombFJXAg',
  },
  50: {
    phrase: 'Ні хуя собі!',
    play: 'Данко',
    phraseN: '28',
    telegramStickerId: 'CAADAgADKAAD09KeCuprNINvBJm4Ag',
  },
  51: {
    phrase: 'Што такоє? Што, спокойно ходіть нє можетє?',
    play: 'До хуя масла',
    phraseN: '7',
    telegramStickerId: 'CAADAgADKQAD09KeCsPOCZU19CcAAQI',
  },
  52: {
    phrase: 'Там масла дохуя!',
    play: 'До хуя масла',
    phraseN: '9',
    telegramStickerId: '',
  },
  53: {
    phrase: 'Скорость охуєвающа',
    play: 'До хуя масла',
    phraseN: '20',
    telegramStickerId: 'CAADAgADKgAD09KeChMoWBIgATMWAg',
  },
  54: {
    phrase: 'Люда, шо ми стоїмо? Щас, знаєш, скіки долбойобів набіжить?',
    play: 'До хуя масла',
    phraseN: '33',
    telegramStickerId: '',
  },
  55: {
    phrase: 'Ето кайф, марожено!',
    play: 'До хуя масла',
    phraseN: '41',
    telegramStickerId: '',
  },
  56: {
    phrase: 'І з тобою, дєд, таке буде, єслі дохуя масла з’їси',
    play: 'До хуя масла',
    phraseN: '60',
    telegramStickerId: 'CAADAgADKwAD09KeCg3zqPwnEnBvAg',
  },
  57: {
    phrase: 'А я тєбє говоріл, што когда-нібудь етот дєнь настанєт, ето будєт, а ти нє вєріла',
    play: 'До хуя масла',
    phraseN: '69',
    telegramStickerId: '',
  },
  58: {
    phrase: 'Та, блядська печінка… Hу наливай!',
    play: 'Кацапи',
    phraseN: '73',
    telegramStickerId: 'CAADAgADLAAD09KeCvaMwFjT9SwfAg',
  },
  59: {
    phrase: 'Я єбу такі ваpіанти!',
    play: 'Кацапи',
    phraseN: '166',
    telegramStickerId: 'CAADAgADLQAD09KeCikxT1miSa_UAg',
  },
  60: {
    phrase: 'Я тєбя за то уважаю, Миша, шо ти pісковий паpєнь',
    play: 'Кацапи',
    phraseN: '168',
    telegramStickerId: 'CAADAgADLgAD09KeCkS2mVdtGzFZAg',
  },
  61: {
    phrase: 'Да йоб твою мать, нахуя мнє піздєть?',
    play: 'Кацапи',
    phraseN: '178',
    telegramStickerId: 'CAADAgADLwAD09KeCv-9jYZ1SWCIAg',
  },
  62: {
    phrase: '[Всі зловісно мовчать]',
    play: 'Кацапи',
    phraseN: '195',
    telegramStickerId: 'CAADAgADMAAD09KeCoGXEeXDWfyWAg',
  },
  63: {
    phrase: 'Я что-то юмоpа-то нє пооонял…',
    play: 'Кацапи',
    phraseN: '222',
    telegramStickerId: 'CAADAgADMQAD09KeCp_j_bPtEF7YAg',
  },
  64: {
    phrase: 'Оце і все?',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '11',
    telegramStickerId: '',
  },
  65: {
    phrase: 'Нє',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '13',
    telegramStickerId: 'CAADAgADMgAD09KeCoM__0_MGYsaAg',
  },
  66: {
    phrase: 'Та то всьо хуйня',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '19',
    telegramStickerId: 'CAADAgADMwAD09KeCh_QhemBHjd6Ag',
  },
  67: {
    phrase: 'Та яка хуйня, в книзі написано!',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '22',
    telegramStickerId: '',
  },
  68: {
    phrase: 'От, жалко пацана',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '91',
    telegramStickerId: '',
  },
  69: {
    phrase: 'Разниє случаї єсть',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '94',
    telegramStickerId: 'CAADAgADNAAD09KeChc_zfh83Z6ZAg',
  },
  70: {
    phrase: 'Боже мой, я етого нє винєсу',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '145',
    telegramStickerId: '',
  },
  71: {
    phrase: 'Вєдь ви нє хотітє етого?',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '224',
    telegramStickerId: '',
  },
  72: {
    phrase: 'Я, собствєно…',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '279',
    telegramStickerId: 'CAADAgADNQAD09KeCmXC41IlQwABjgI',
  },
  73: {
    phrase: 'Я больше не можу так жить! Кругом якась хуйня, скрізь підараси',
    play: 'Місце встрєчі ізмєніть ніззя, блядь',
    phraseN: '286',
    telegramStickerId: 'CAADAgADNgAD09KeCk5kvUiTEAwVAg',
  },
  74: {
    phrase: 'Дозвольте к Вам, Клім Моісєйович поважний, Звернутися у справах очень важних',
    play: 'Пацавата історія',
    phraseN: '36',
    telegramStickerId: '',
  },
  75: {
    phrase: 'Нєт!',
    play: 'Пацавата історія',
    phraseN: '61',
    telegramStickerId: '',
  },
  76: {
    phrase: '[Німа сцена]',
    play: 'Пацавата історія',
    phraseN: '116',
    telegramStickerId: 'CAADAgADNwAD09KeClXCWD3C6WmQAg',
  },
  77: {
    phrase: 'Іначе нам ніззя нікак',
    play: 'Пацавата історія',
    phraseN: '124',
    telegramStickerId: 'CAADAgADOAAD09KeCjK-_lfkujrVAg',
  },
  78: {
    phrase: 'По-мойму, будєт заїбісь!',
    play: 'Пацавата історія',
    phraseN: '138',
    telegramStickerId: 'CAADAgADOQAD09KeCk0Q-tlRs0vFAg',
  },
  79: {
    phrase: 'А вийдєт с етого хуйня',
    play: 'Пацавата історія',
    phraseN: '142',
    telegramStickerId: 'CAADAgADOgAD09KeCslhPXRubHu0Ag',
  },
  80: {
    phrase: 'Канєчно, я',
    play: 'Пацавата історія',
    phraseN: '146',
    telegramStickerId: 'CAADAgADOwAD09KeCh0DW59nAAHKwAI',
  },
  81: {
    phrase: 'К тєбє прийшов я нє таясь, Тьми вогкой пацаватий Князь',
    play: 'Пацавата історія',
    phraseN: '169',
    telegramStickerId: '',
  },
  82: {
    phrase: 'Мнє кажеться, что ету фразу Проізносіть нє стоіт сразу',
    play: 'Пацавата історія',
    phraseN: '180',
    telegramStickerId: 'CAADAgADPAAD09KeCnAa6D6TfY5BAg',
  },
  83: {
    phrase: 'А, єслі можно, мєдлєнєй…',
    play: 'Пацавата історія',
    phraseN: '181',
    telegramStickerId: 'CAADAgADPQAD09KeCuJa2D4eEw77Ag',
  },
  84: {
    phrase: 'Вам віднєй',
    play: 'Пацавата історія',
    phraseN: '184',
    telegramStickerId: 'CAADAgADPgAD09KeCgISCkS8mxq4Ag',
  },
  85: {
    phrase: 'Не вєрю! Нє вєрю!',
    play: 'Пацавата історія',
    phraseN: '249',
    telegramStickerId: '',
  },
  86: {
    phrase: 'Піздєц',
    play: 'Піздєц',
    phraseN: '1',
    telegramStickerId: '',
  },
  87: {
    phrase: 'З цього місця, будь ласка, з подробицями, Альфреде Юхимович',
    play: 'Піздєц',
    phraseN: '39',
    telegramStickerId: 'CAADAgADPwAD09KeCo3h-DbGV91FAg',
  },
  88: {
    phrase: 'Я вас прошу, не отвлєкайтєсь, шановний Альфреде Юхимович',
    play: 'Піздєц',
    phraseN: '75',
    telegramStickerId: 'CAADAgADQAAD09KeCpAszwaYmwABDgI',
  },
  89: {
    phrase: 'Як ви сказали, Альфреде Юхимович? Повторіть',
    play: 'Піздєц',
    phraseN: '81',
    telegramStickerId: 'CAADAgADQQAD09KeCtU4VvQBnioKAg',
  },
  90: {
    phrase: 'Тогда надо воду злівать!',
    play: 'Піздєц',
    phraseN: '98',
    telegramStickerId: 'CAADAgADQgAD09KeCjDqOjlgnrxhAg',
  },
  91: {
    phrase: 'От дє кайф ловлять!',
    play: 'Піздєц',
    phraseN: '141',
    telegramStickerId: '',
  },
  92: {
    phrase: 'От все одно – заєбісь жизнь!',
    play: 'Піздєц',
    phraseN: '164',
    telegramStickerId: 'CAADAgADQwAD09KeCmusmvK3qx8-Ag',
  },
  93: {
    phrase: 'Відкривай, блядь!',
    play: 'Піздєц',
    phraseN: '165',
    telegramStickerId: '',
  },
  94: {
    phrase: 'Та одін хуй – раз живьом! Эх жизнь хуйовая!',
    play: 'Піздєц',
    phraseN: '169',
    telegramStickerId: '',
  },
  95: {
    phrase: 'Чєловєк чєловєку – друг, товарищ і брат',
    play: 'Піздєц',
    phraseN: '186',
    telegramStickerId: 'CAADAgADRAAD09KeCgpbkhYHfZMQAg',
  },
  96: {
    phrase: 'Ги-ги! Ото нєхуйово!',
    play: 'Піздєц',
    phraseN: '231',
    telegramStickerId: 'CAADAgADRQAD09KeCqz8bIypyXj6Ag',
  },
  97: {
    phrase: 'Ти не гуманіст, Омелян',
    play: 'Піздєц',
    phraseN: '268',
    telegramStickerId: '',
  },
  98: {
    phrase: 'Какая ви нєрвная – я єбу!',
    play: 'Піздєц',
    phraseN: '375',
    telegramStickerId: 'CAADAgADRgAD09KeCmB9xPbqBxD8Ag',
  },
  99: {
    phrase: 'Га?',
    play: 'Хвороба Івасика',
    phraseN: '36',
    telegramStickerId: 'CAADAgADRwAD09KeCrP1Z5uNRMrXAg',
  },
  100: {
    phrase: 'А хто це к нам лізе?',
    play: 'Хвороба Івасика',
    phraseN: '44',
    telegramStickerId: 'CAADAgADSAAD09KeCkILPms6czLSAg',
  },
  101: {
    phrase: 'Та то якесь випадєніє',
    play: 'Хвороба Івасика',
    phraseN: '46',
    telegramStickerId: 'CAADAgADSQAD09KeCi6_x2NdYUmbAg',
  },
  102: {
    phrase: 'Ми ковалі нашого щастя, Івасику!',
    play: 'Хвороба Івасика',
    phraseN: '68',
    telegramStickerId: 'CAADAgADSgAD09KeCgLbS2dn-2iCAg',
  },
  103: {
    phrase: 'Настане день, і усі хвороби буде знищено',
    play: 'Хвороба Івасика',
    phraseN: '82',
    telegramStickerId: '',
  },
  104: {
    phrase: 'Мирон Опанасович, шо в нас по плану?',
    play: 'Цікаві досліди',
    phraseN: '32',
    telegramStickerId: 'CAADAgADSwAD09KeCkckoXAigbc0Ag',
  },
  105: {
    phrase: 'Одна думка, шо Бог є – це вже хуйня, Мирон Опанасович',
    play: 'Цікаві досліди',
    phraseN: '38',
    telegramStickerId: '',
  },
  106: {
    phrase: 'Звичайно, хуйня, Зоя Жорівна, ще й яка хуйня',
    play: 'Цікаві досліди',
    phraseN: '41',
    telegramStickerId: 'CAADAgADTAAD09KeCiooWXAcQyWrAg',
  },
  107: {
    phrase: 'Це ідеалістичний онанізм',
    play: 'Цікаві досліди',
    phraseN: '42',
    telegramStickerId: 'CAADAgADTQAD09KeCvQheYOZ42ShAg',
  },
  108: {
    phrase: 'Спокійніше, Зоя Жорівна, спокійніше',
    play: 'Цікаві досліди',
    phraseN: '58',
    telegramStickerId: 'CAADAgADTgAD09KeCnolQ-HmS4wgAg',
  },
  109: {
    phrase: 'Досить, Гриша, сідай, п’ять',
    play: 'Цікаві досліди',
    phraseN: '73',
    telegramStickerId: 'CAADAgADTwAD09KeCovx1vl5gJlEAg',
  },
  110: {
    phrase: 'Миша, продовжуй',
    play: 'Цікаві досліди',
    phraseN: '74',
    telegramStickerId: '',
  },
  111: {
    phrase: 'Сідай, п’ять',
    play: 'Цікаві досліди',
    phraseN: '90',
    telegramStickerId: '',
  },
  112: {
    phrase: 'Починаємо вивчення нового матеріалу',
    play: 'Цікаві досліди',
    phraseN: '91',
    telegramStickerId: '',
  },
  113: {
    phrase: 'Будь ласка, Мирон Опанасович',
    play: 'Цікаві досліди',
    phraseN: '92',
    telegramStickerId: 'CAADAgADUAAD09KeCvsBdcx7fYD-Ag',
  },
  114: {
    phrase: 'Діти, хто це?',
    play: 'Цікаві досліди',
    phraseN: '95',
    telegramStickerId: '',
  },
  115: {
    phrase: 'І знов двійка, Носенко',
    play: 'Цікаві досліди',
    phraseN: '115',
    telegramStickerId: 'CAADAgADUQAD09KeCiGZ7XhpmBToAg',
  },
  116: {
    phrase: 'Продовжуйте, Зоя Жорівна',
    play: 'Цікаві досліди',
    phraseN: '117',
    telegramStickerId: 'CAADAgADUgAD09KeCu5jS_HQLenlAg',
  },
  117: {
    phrase: 'От шкода, знову часу не вистачило',
    play: 'Цікаві досліди',
    phraseN: '132',
    telegramStickerId: '',
  },
  118: {
    phrase: 'Зробимо висновки, діти',
    play: 'Цікаві досліди',
    phraseN: '133',
    telegramStickerId: '',
  },
  119: {
    phrase: 'Бога нема, а є природа',
    play: 'Цікаві досліди',
    phraseN: '134',
    telegramStickerId: '',
  },
  120: {
    phrase: 'Природу треба міняти і знищувать все, що в ній непотрібно',
    play: 'Цікаві досліди',
    phraseN: '135',
    telegramStickerId: '',
  },
  121: {
    phrase: 'А ти, Носенко, дай щоденик, і щоб завтра твій батько був у школі',
    play: 'Цікаві досліди',
    phraseN: '136',
    telegramStickerId: '',
  },
  122: {
    phrase: 'Вже років три',
    play: 'Діана',
    phraseN: '291',
    telegramStickerId: 'CAADAgADVAAD09KeCnZbdmC557A9Ag',
  },
  123: {
    phrase: 'Какой чудак, єй богу…',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '115',
    telegramStickerId: 'CAADAgADVQAD09KeCg6LMI2O96wTAg',
  },
  124: {
    phrase: 'Я знаю',
    play: 'Павлік Морозов',
    phraseN: '57',
    telegramStickerId: 'CAADAgADVgAD09KeCgMKGfI_tm9nAg',
  },
  125: {
    phrase: 'От падла!',
    play: 'Павлік Морозов',
    phraseN: '68',
    telegramStickerId: '',
  },
  126: {
    phrase: 'Це знають ще у яслах малi дiти, Що лучше перебдiть, нiж недобдiти',
    play: 'Павлік Морозов',
    phraseN: '99',
    telegramStickerId: '',
  },
  127: {
    phrase:
      'Так налякав, що я ледь не усрався в свої красивi новi галіфе, і нову вєщь красiву чуть не спортив',
    play: 'Павлік Морозов',
    phraseN: '186',
    telegramStickerId: 'CAADAgADVwAD09KeCgX23nYVrWrHAg',
  },
  128: {
    phrase: 'Куди не кину оком стомленим – кругом хуйня',
    play: 'Павлік Морозов',
    phraseN: '268',
    telegramStickerId: 'CAADAgADWAAD09KeCqyNfdBLEe2BAg',
  },
  129: {
    phrase: 'Всьо-такі нам до Європи срать і срать єщьо',
    play: 'Павлік Морозов',
    phraseN: '448',
    telegramStickerId: '',
  },
  130: {
    phrase:
      'Сказати вам по правдi, не люблю я тих блядських теревенiв, бо не вірю у силу слова я, а вiрю в силу пiздюлєй',
    play: 'Павлік Морозов',
    phraseN: '790',
    telegramStickerId: 'CAADAgADWQAD09KeCqGhmRjPPtCYAg',
  },
  131: {
    phrase: 'Ну, не клянись, то грiх',
    play: 'Павлік Морозов',
    phraseN: '1269',
    telegramStickerId: '',
  },
  132: {
    phrase: 'Чого мовчиш?',
    play: 'Остановісь, мгновєньє – ти прєкрасно!',
    phraseN: '47',
    telegramStickerId: '',
  },
  133: {
    phrase: 'Очєнь даже напрасно',
    play: 'Остановісь, мгновєньє – ти прєкрасно!',
    phraseN: '68',
    telegramStickerId: '',
  },
  134: {
    phrase: 'На блядки підем сьогодня?',
    play: 'Остановісь, мгновєньє – ти прєкрасно!',
    phraseN: '182',
    telegramStickerId: 'CAADAgADWgAD09KeCnYmmo2q5knQAg',
  },
  135: {
    phrase: 'Вобщє, умнєйша, опитнєйша людина!',
    play: 'Сноби',
    phraseN: '57',
    telegramStickerId: 'CAADAgADWwAD09KeCtI8v2cbwmv1Ag',
  },
  136: {
    phrase: 'Ти, Поля, сначала думай, а потом спрашуй!',
    play: 'Сноби',
    phraseN: '185',
    telegramStickerId: 'CAADAgADXAAD09KeCpB3qyVh_rxCAg',
  },
  137: {
    phrase: 'Просто так нічого не буває',
    play: 'Нірвана',
    phraseN: '56',
    telegramStickerId: 'CAADAgADXQAD09KeCrQ--2ydp3VmAg',
  },
  138: {
    phrase: 'Це як у Ніцше написано: Коли ти дивишся в безодню, безодня дивиться на тебе',
    play: 'Нірвана',
    phraseN: '140',
    telegramStickerId: '',
  },
  139: {
    phrase: 'Колись порядок був, нахуй, не те, шо січас!',
    play: 'Казка про рєпку, або Хулі не ясно?',
    phraseN: '64',
    telegramStickerId: '',
  },
  140: {
    phrase: 'Чого тобі треба?',
    play: 'Йоко і самураї',
    phraseN: '114',
    telegramStickerId: 'CAADAgADXgAD09KeCv7e3evxUZwWAg',
  },
  141: {
    phrase: 'Какой ти скучний! Це я скучний! А вона, блядь, весела!',
    play: 'Нірвана',
    phraseN: '134',
    telegramStickerId: 'CAADAgADXwAD09KeCu7VLawxhv1zAg',
  },
  142: {
    phrase: '[Відповіддю їй служать удари голови об стінку]',
    play: 'Місце встрєчі ізмєніть ніззя, блядь!',
    phraseN: '259',
    telegramStickerId: 'CAADAgADYAAD09KeCiQ5Jp5mBhuMAg',
  },
  143: {
    phrase: 'Кожа як у бога',
    play: 'Васіліса Єгоровна і мужичкі',
    phraseN: '36',
    telegramStickerId: 'CAADAgADYQAD09KeCi4eKz8OuqWFAg',
  },
  144: {
    phrase: 'Дурні пацаваті! Я вічно буду жить',
    play: 'Король Літр',
    phraseN: '657',
    telegramStickerId: 'CAADAgADYgAD09KeCtqDMKvlGuaGAg',
  },
  145: {
    phrase: '[З вани долинають звуки води і веселий регіт Красної Шапочки]',
    play: 'Місце встрєчі ізмєніть ніззя, блядь!',
    phraseN: '31',
    telegramStickerId: '',
  },
  146: {
    phrase: '[Під його веселий регіт завіса повільно закривається]',
    play: 'Король Літр',
    phraseN: '728',
    telegramStickerId: 'CAADAgADYwAD09KeCvgLKF5p2eC-Ag',
  },
  147: {
    phrase:
      'Вам тільки би горілки засадить та мамку бідну на печі єбати, аж дим із хати йде. А потім чаю посьорбати і кидати сокиру в паралізовану бабуню, в унітаза хуярить чобітьми',
    play: 'Гамлєт, або Феномен датського кацапізма',
    phraseN: '80',
    telegramStickerId: 'CAADAgADZAAD09KeCruswhYD13YvAg',
  },
  148: {
    phrase: 'Я люблю, щоб у мене хазяйство було',
    play: 'Остановісь, мгновєньє – ти прєкрасно!',
    phraseN: '205',
    telegramStickerId: '',
  },
  149: {
    phrase: 'Руб єсть?',
    play: 'Васіліса Єгоровна і мужичкі',
    phraseN: '99',
    telegramStickerId: 'CAADAgADZQAD09KeCmfARqGiAyZ4Ag',
  },
  150: {
    phrase: 'Звідки ви знаєте, дядя?',
    play: 'Піздєц',
    phraseN: '250',
    telegramStickerId: 'CAADAgADbQAD09KeCt69yJiAUE9hAg',
  },
  151: {
    phrase: 'Правда, дядя Савка?',
    play: 'Герой нашого часу. Повість друга',
    phraseN: '215',
    telegramStickerId: 'CAADAgADZgAD09KeCqPZRtgkRejpAg',
  },
  152: {
    phrase: 'Привіт, “Компана”! Я вам почитати принесла!',
    play: 'Нірвана',
    phraseN: '170',
    telegramStickerId: 'CAADAgADbgAD09KeCmzHccGwfg9-Ag',
  },
};
